@echo off
cd /d "%~dp0"
echo Exporting Power BI-ready dashboard tables...
.\.venv\Scripts\python.exe src\export_dashboard_data.py
echo Creating current next-day energy forecasts...
.\.venv\Scripts\python.exe src\generate_future_forecasts.py
echo Starting the Streamlit review dashboard...
.\.venv\Scripts\streamlit.exe run app\streamlit_app.py
